spring:
  datasource:
    url: jdbc:mysql://saenaljigidb.cdis22ekwo82.ap-northeast-2.rds.amazonaws.com:3306/saenaljigi?useSSL=false&serverTimezone=UTC
    username: saenaljigi
    password: saenaljigi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #update는 데이터 저장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  jwt:
    secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


#server:
#  address: 0.0.0.0
#  port: 8080
